FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

EXPOSE 10000

CMD uvicorn backend.main:app --host 0.0.0.0 --port 8000 & \
    streamlit run app.py \
    --server.address=0.0.0.0 \
    --server.port=${PORT:-10000}